import React from 'react';
import { Row, Col } from 'react-simple-flex-grid';
import { DatePicker } from "@blueprintjs/datetime";
import { Card, Elevation, Tab, Tabs } from "@blueprintjs/core";
// import { Table, Column } from "@blueprintjs/table";
import { TableComponent } from './tableComponent';
import { ReordableTable } from './reordableTable.js';
import { SortableTable } from './sortableTable.js';
import EditProfilePanel from './editProfilePanel';
import ExtraInfoPanel from './extraInfoPanel';
import MomentLocaleUtils from 'react-day-picker/moment';
import 'moment/locale/bg';
import "../../../node_modules/@blueprintjs/datetime/lib/css/blueprint-datetime.css";
import "../../../node_modules/@blueprintjs/table/lib/css/table.css";

const sampleDataX = {
    '2018-07-17' : {
      "0-0": "i",
      "0-1": "212121/ 1231312",
      "0-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "0-3": "03.07.2018",
      "0-4": "ВЛАДИСЛАВ ГАНЕВ",
      "0-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
  },
    '2018-07-09' : {
      "0-0": "i",
      "0-1": "01312/ 1231312",
      "0-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "0-3": "09.07.2018",
      "0-4": "ВЛАДИСЛАВ ГАНЕВ",
      "0-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
      "1-0": "i",
      "1-1": "01312/ 1231312",
      "1-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "1-3": "09.07.2018",
      "1-4": "ВЛАДИСЛАВ ГАНЕВ",
      "1-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
      "2-0": "i",
      "2-1": "01312/ 1231312",
      "2-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "2-3": "09.07.2018",
      "2-4": "ВЛАДИСЛАВ ГАНЕВ",
      "2-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
  },
    '2018-07-10' : {
      "0-0": "i",
      "0-1": "78798/87987",
      "0-2": "ТИП 1",
      "0-3": "10.07.2018",
      "0-4": "ВЛАДИСЛАВ ГАНЕВ",
      "0-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
      "1-0": "i",
      "1-1": "85233/44445",
      "1-2": "ТИП 2",
      "1-3": "10.07.2018",
      "1-4": "ВЛАДИСЛАВ ГАНЕВ",
      "1-5": "In hac habitasse platea dictumst. Vestibulum faucibus elit vitae iaculis cursus. Sed porttitor ex velit, eu sollicitudin nunc sollicitudin quis. Donec id arcu vel ex tempus varius et non ex. Praesent eu pretium diam. Donec in dapibus neque. Nunc malesuada vestibulum luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dapibus ac tellus at ultrices. Donec neque diam, rutrum nec malesuada eget, consequat ac diam.",
      "2-0": "i",
      "2-1": "16783/64234",
      "2-2": "ТИП 3",
      "2-3": "10.07.2018",
      "2-4": "ВЛАДИСЛАВ ГАНЕВ",
      "2-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
      "3-0": "i",
      "3-1": "96345/135473",
      "3-2": "ТИП 4",
      "3-3": "10.07.2018",
      "3-4": "ВЛАДИСЛАВ ГАНЕВ",
      "3-5": "In hac habitasse platea dictumst. Vestibulum faucibus elit vitae iaculis cursus. Sed porttitor ex velit, eu sollicitudin nunc sollicitudin quis. Donec id arcu vel ex tempus varius et non ex. Praesent eu pretium diam. Donec in dapibus neque. Nunc malesuada vestibulum luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dapibus ac tellus at ultrices. Donec neque diam, rutrum nec malesuada eget, consequat ac diam.",
      "4-0": "i",
      "4-1": "123123/523454",
      "4-2": "ТИП 5",
      "4-3": "10.07.2018",
      "4-4": "ВЛАДИСЛАВ ГАНЕВ",
      "4-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
  },
    '2018-07-11' : {
      "0-0": "i",
      "0-1": "01312/ 1231312",
      "0-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "0-3": "11.07.2018",
      "0-4": "ВЛАДИСЛАВ ГАНЕВ",
      "0-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
      "1-0": "i",
      "1-1": "01312/ 1231312",
      "1-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "1-3": "11.07.2018",
      "1-4": "ВЛАДИСЛАВ ГАНЕВ",
      "1-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
      "2-0": "i",
      "2-1": "01312/ 1231312",
      "2-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "2-3": "11.07.2018",
      "2-4": "ВЛАДИСЛАВ ГАНЕВ",
      "2-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
  },
    '2018-07-12' : {
      "0-0": "i",
      "0-1": "01312/ 1231312",
      "0-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "0-3": "12.07.2018",
      "0-4": "ВЛАДИСЛАВ ГАНЕВ",
      "0-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
      "1-0": "i",
      "1-1": "01312/ 1231312",
      "1-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "1-3": "12.07.2018",
      "1-4": "ВЛАДИСЛАВ ГАНЕВ",
      "1-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
      "2-0": "i",
      "2-1": "01312/ 1231312",
      "2-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "2-3": "12.07.2018",
      "2-4": "ВЛАДИСЛАВ ГАНЕВ",
      "2-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
  },
    '2018-07-13' : {
      "0-0": "i",
      "0-1": "01312/ 1231312",
      "0-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "0-3": "13.07.2018",
      "0-4": "ВЛАДИСЛАВ ГАНЕВ",
      "0-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
      "1-0": "i",
      "1-1": "01312/ 1231312",
      "1-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "1-3": "13.07.2018",
      "1-4": "ВЛАДИСЛАВ ГАНЕВ",
      "1-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
      "2-0": "i",
      "2-1": "01312/ 1231312",
      "2-2": "ПОЕТ АНГАЖИМЕНТ ОТ ДЛЪЖНИКА",
      "2-3": "13.07.2018",
      "2-4": "ВЛАДИСЛАВ ГАНЕВ",
      "2-5": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod.",
  },
}

const sampleDataY = {
  '2018-07-17' : [
    ["i", "23523/ 4534533", "СТАТУС 21", "09.07.2018", "Иван Иванов", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "23451/ 5353577", "СТАТУС 22", "09.07.2018", "Георги Георгиев", "In hac habitasse platea dictumst. Vestibulum faucibus elit vitae iaculis cursus. Sed porttitor ex velit, eu sollicitudin nunc sollicitudin quis. Donec id arcu vel ex tempus varius et non ex. Praesent eu pretium diam. Donec in dapibus neque. Nunc malesuada vestibulum luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dapibus ac tellus at ultrices. Donec neque diam, rutrum nec malesuada eget, consequat ac diam."],
    ["i", "23423/ 9894367", "СТАТУС 8", "09.07.2018", "Иванка Иванова", "Morbi pellentesque urna mollis velit aliquet, volutpat egestas metus varius. In tristique vitae enim vel mollis. Maecenas venenatis nibh vitae quam tincidunt pharetra. Nulla vestibulum lacus velit, at gravida massa varius nec. Phasellus vitae sapien quis nibh efficitur mollis. Curabitur aliquam neque nec augue elementum, a fermentum mi tincidunt. In augue elit, ultricies sed porttitor ut, pulvinar a sapien. Phasellus ut eros diam. Aenean vel pretium orci. Donec diam elit, suscipit quis nisl vel, varius consequat neque."],
  ],
  '2018-07-09' : [
    ["i", "23523/ 4534533", "СТАТУС 21", "09.07.2018", "Иван Иванов", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "23451/ 5353577", "СТАТУС 22", "09.07.2018", "Георги Георгиев", "In hac habitasse platea dictumst. Vestibulum faucibus elit vitae iaculis cursus. Sed porttitor ex velit, eu sollicitudin nunc sollicitudin quis. Donec id arcu vel ex tempus varius et non ex. Praesent eu pretium diam. Donec in dapibus neque. Nunc malesuada vestibulum luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dapibus ac tellus at ultrices. Donec neque diam, rutrum nec malesuada eget, consequat ac diam."],
    ["i", "23423/ 9894367", "СТАТУС 8", "09.07.2018", "Иванка Иванова", "Morbi pellentesque urna mollis velit aliquet, volutpat egestas metus varius. In tristique vitae enim vel mollis. Maecenas venenatis nibh vitae quam tincidunt pharetra. Nulla vestibulum lacus velit, at gravida massa varius nec. Phasellus vitae sapien quis nibh efficitur mollis. Curabitur aliquam neque nec augue elementum, a fermentum mi tincidunt. In augue elit, ultricies sed porttitor ut, pulvinar a sapien. Phasellus ut eros diam. Aenean vel pretium orci. Donec diam elit, suscipit quis nisl vel, varius consequat neque."],
  ],
  '2018-07-10' : [
    ["i", "36453/ 1456465", "СТАТУС 2", "10.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
  ],
  '2018-07-11' : [
    ["i", "36453/ 1456465", "СТАТУС 2", "11.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "34534/ 7678985", "СТАТУС 5", "11.07.2018", "Трайчо Трайков", "Nulla tempor orci elit, vitae gravida nulla placerat id. Aliquam sodales lorem a arcu dapibus eleifend vitae vitae est. Nunc finibus lectus vel sem ullamcorper lobortis. In ut ultrices erat. Cras porttitor finibus diam nec luctus. Suspendisse in augue ipsum. Suspendisse potenti. Maecenas et eros ac nisl bibendum tincidunt nec eget leo. Sed sit amet neque eget justo condimentum convallis. Cras eget nisl laoreet, dapibus libero at, vulputate arcu. In dictum lacinia orci, nec dignissim dolor ultricies at. Integer ullamcorper, nisi non mattis iaculis, dolor massa mattis lacus, sollicitudin feugiat orci nisi sed nulla. Mauris quis tristique nibh, sit amet scelerisque nibh."],
    ["i", "01312/ 4531135", "СТАТУС 21", "11.07.2018", "Здравко Здравков", "Sed molestie commodo nibh, quis tincidunt arcu dapibus vitae. Sed enim urna, interdum id auctor non, rutrum volutpat nulla. Etiam ut cursus magna, eget malesuada sapien. Nulla finibus tortor finibus leo molestie faucibus. Integer vel sapien porta, pellentesque felis sed, fermentum arcu. Suspendisse a massa ante. Nunc euismod nisl eros, ut pretium odio consequat ac."],
    ["i", "46783/ 4537837", "СТАТУС 24", "11.07.2018", "Желязко Желязков", "Sed felis dui, finibus nec suscipit vel, blandit ut sapien. Cras ornare odio elit, sed dignissim urna egestas hendrerit. Maecenas aliquam enim vitae commodo rhoncus. In porttitor ullamcorper felis, quis sodales neque eleifend ut. Sed non tellus libero. Mauris in quam id nulla dignissim commodo ac nec tellus. Nullam sagittis pellentesque neque ut dictum. Ut tristique, quam sit amet consequat porta, mi nisl lacinia felis, sit amet auctor turpis dolor quis arcu. Donec quis mi nec est elementum condimentum. Vestibulum luctus pretium euismod. Aliquam ut justo sed orci faucibus imperdiet. Quisque quis erat lacinia, egestas lorem ut, mollis mauris. In convallis at nisi aliquet laoreet. Nulla aliquam consequat gravida. Nullam sollicitudin a orci ut congue. Aliquam sed quam blandit, euismod enim eu, luctus sapien."],
    ["i", "23523/ 4534533", "СТАТУС 21", "11.07.2018", "Иван Иванов", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "23451/ 5353577", "СТАТУС 22", "11.07.2018", "Георги Георгиев", "In hac habitasse platea dictumst. Vestibulum faucibus elit vitae iaculis cursus. Sed porttitor ex velit, eu sollicitudin nunc sollicitudin quis. Donec id arcu vel ex tempus varius et non ex. Praesent eu pretium diam. Donec in dapibus neque. Nunc malesuada vestibulum luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dapibus ac tellus at ultrices. Donec neque diam, rutrum nec malesuada eget, consequat ac diam."],
    ["i", "23423/ 9894367", "СТАТУС 8", "11.07.2018", "Иванка Иванова", "Morbi pellentesque urna mollis velit aliquet, volutpat egestas metus varius. In tristique vitae enim vel mollis. Maecenas venenatis nibh vitae quam tincidunt pharetra. Nulla vestibulum lacus velit, at gravida massa varius nec. Phasellus vitae sapien quis nibh efficitur mollis. Curabitur aliquam neque nec augue elementum, a fermentum mi tincidunt. In augue elit, ultricies sed porttitor ut, pulvinar a sapien. Phasellus ut eros diam. Aenean vel pretium orci. Donec diam elit, suscipit quis nisl vel, varius consequat neque."],
    ["i", "36453/ 1456465", "СТАТУС 2", "11.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "34534/ 7678985", "СТАТУС 5", "11.07.2018", "Трайчо Трайков", "Nulla tempor orci elit, vitae gravida nulla placerat id. Aliquam sodales lorem a arcu dapibus eleifend vitae vitae est. Nunc finibus lectus vel sem ullamcorper lobortis. In ut ultrices erat. Cras porttitor finibus diam nec luctus. Suspendisse in augue ipsum. Suspendisse potenti. Maecenas et eros ac nisl bibendum tincidunt nec eget leo. Sed sit amet neque eget justo condimentum convallis. Cras eget nisl laoreet, dapibus libero at, vulputate arcu. In dictum lacinia orci, nec dignissim dolor ultricies at. Integer ullamcorper, nisi non mattis iaculis, dolor massa mattis lacus, sollicitudin feugiat orci nisi sed nulla. Mauris quis tristique nibh, sit amet scelerisque nibh."],
    ["i", "01312/ 4531135", "СТАТУС 21", "11.07.2018", "Здравко Здравков", "Sed molestie commodo nibh, quis tincidunt arcu dapibus vitae. Sed enim urna, interdum id auctor non, rutrum volutpat nulla. Etiam ut cursus magna, eget malesuada sapien. Nulla finibus tortor finibus leo molestie faucibus. Integer vel sapien porta, pellentesque felis sed, fermentum arcu. Suspendisse a massa ante. Nunc euismod nisl eros, ut pretium odio consequat ac."],
    ["i", "36453/ 1456465", "СТАТУС 2", "11.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "34534/ 7678985", "СТАТУС 5", "11.07.2018", "Трайчо Трайков", "Nulla tempor orci elit, vitae gravida nulla placerat id. Aliquam sodales lorem a arcu dapibus eleifend vitae vitae est. Nunc finibus lectus vel sem ullamcorper lobortis. In ut ultrices erat. Cras porttitor finibus diam nec luctus. Suspendisse in augue ipsum. Suspendisse potenti. Maecenas et eros ac nisl bibendum tincidunt nec eget leo. Sed sit amet neque eget justo condimentum convallis. Cras eget nisl laoreet, dapibus libero at, vulputate arcu. In dictum lacinia orci, nec dignissim dolor ultricies at. Integer ullamcorper, nisi non mattis iaculis, dolor massa mattis lacus, sollicitudin feugiat orci nisi sed nulla. Mauris quis tristique nibh, sit amet scelerisque nibh."],
    ["i", "01312/ 4531135", "СТАТУС 21", "11.07.2018", "Здравко Здравков", "Sed molestie commodo nibh, quis tincidunt arcu dapibus vitae. Sed enim urna, interdum id auctor non, rutrum volutpat nulla. Etiam ut cursus magna, eget malesuada sapien. Nulla finibus tortor finibus leo molestie faucibus. Integer vel sapien porta, pellentesque felis sed, fermentum arcu. Suspendisse a massa ante. Nunc euismod nisl eros, ut pretium odio consequat ac."],
  ],
  '2018-07-12' : [
    ["i", "36453/ 1456465", "СТАТУС 2", "12.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "46783/ 4537837", "СТАТУС 24", "12.07.2018", "Желязко Желязков", "Sed felis dui, finibus nec suscipit vel, blandit ut sapien. Cras ornare odio elit, sed dignissim urna egestas hendrerit. Maecenas aliquam enim vitae commodo rhoncus. In porttitor ullamcorper felis, quis sodales neque eleifend ut. Sed non tellus libero. Mauris in quam id nulla dignissim commodo ac nec tellus. Nullam sagittis pellentesque neque ut dictum. Ut tristique, quam sit amet consequat porta, mi nisl lacinia felis, sit amet auctor turpis dolor quis arcu. Donec quis mi nec est elementum condimentum. Vestibulum luctus pretium euismod. Aliquam ut justo sed orci faucibus imperdiet. Quisque quis erat lacinia, egestas lorem ut, mollis mauris. In convallis at nisi aliquet laoreet. Nulla aliquam consequat gravida. Nullam sollicitudin a orci ut congue. Aliquam sed quam blandit, euismod enim eu, luctus sapien."],
    ["i", "23523/ 4534533", "СТАТУС 21", "12.07.2018", "Иван Иванов", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "23423/ 9894367", "СТАТУС 8", "12.07.2018", "Иванка Иванова", "Morbi pellentesque urna mollis velit aliquet, volutpat egestas metus varius. In tristique vitae enim vel mollis. Maecenas venenatis nibh vitae quam tincidunt pharetra. Nulla vestibulum lacus velit, at gravida massa varius nec. Phasellus vitae sapien quis nibh efficitur mollis. Curabitur aliquam neque nec augue elementum, a fermentum mi tincidunt. In augue elit, ultricies sed porttitor ut, pulvinar a sapien. Phasellus ut eros diam. Aenean vel pretium orci. Donec diam elit, suscipit quis nisl vel, varius consequat neque."],
  ],
  '2018-07-13' : [
    ["i", "36453/ 1456465", "СТАТУС 2", "13.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "34534/ 7678985", "СТАТУС 5", "13.07.2018", "Трайчо Трайков", "Nulla tempor orci elit, vitae gravida nulla placerat id. Aliquam sodales lorem a arcu dapibus eleifend vitae vitae est. Nunc finibus lectus vel sem ullamcorper lobortis. In ut ultrices erat. Cras porttitor finibus diam nec luctus. Suspendisse in augue ipsum. Suspendisse potenti. Maecenas et eros ac nisl bibendum tincidunt nec eget leo. Sed sit amet neque eget justo condimentum convallis. Cras eget nisl laoreet, dapibus libero at, vulputate arcu. In dictum lacinia orci, nec dignissim dolor ultricies at. Integer ullamcorper, nisi non mattis iaculis, dolor massa mattis lacus, sollicitudin feugiat orci nisi sed nulla. Mauris quis tristique nibh, sit amet scelerisque nibh."],
    ["i", "01312/ 4531135", "СТАТУС 21", "13.07.2018", "Здравко Здравков", "Sed molestie commodo nibh, quis tincidunt arcu dapibus vitae. Sed enim urna, interdum id auctor non, rutrum volutpat nulla. Etiam ut cursus magna, eget malesuada sapien. Nulla finibus tortor finibus leo molestie faucibus. Integer vel sapien porta, pellentesque felis sed, fermentum arcu. Suspendisse a massa ante. Nunc euismod nisl eros, ut pretium odio consequat ac."],
    ["i", "46783/ 4537837", "СТАТУС 24", "13.07.2018", "Желязко Желязков", "Sed felis dui, finibus nec suscipit vel, blandit ut sapien. Cras ornare odio elit, sed dignissim urna egestas hendrerit. Maecenas aliquam enim vitae commodo rhoncus. In porttitor ullamcorper felis, quis sodales neque eleifend ut. Sed non tellus libero. Mauris in quam id nulla dignissim commodo ac nec tellus. Nullam sagittis pellentesque neque ut dictum. Ut tristique, quam sit amet consequat porta, mi nisl lacinia felis, sit amet auctor turpis dolor quis arcu. Donec quis mi nec est elementum condimentum. Vestibulum luctus pretium euismod. Aliquam ut justo sed orci faucibus imperdiet. Quisque quis erat lacinia, egestas lorem ut, mollis mauris. In convallis at nisi aliquet laoreet. Nulla aliquam consequat gravida. Nullam sollicitudin a orci ut congue. Aliquam sed quam blandit, euismod enim eu, luctus sapien."],
    ["i", "23523/ 4534533", "СТАТУС 21", "13.07.2018", "Иван Иванов", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "23451/ 5353577", "СТАТУС 22", "13.07.2018", "Георги Георгиев", "In hac habitasse platea dictumst. Vestibulum faucibus elit vitae iaculis cursus. Sed porttitor ex velit, eu sollicitudin nunc sollicitudin quis. Donec id arcu vel ex tempus varius et non ex. Praesent eu pretium diam. Donec in dapibus neque. Nunc malesuada vestibulum luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dapibus ac tellus at ultrices. Donec neque diam, rutrum nec malesuada eget, consequat ac diam."],
    ["i", "23423/ 9894367", "СТАТУС 8", "13.07.2018", "Иванка Иванова", "Morbi pellentesque urna mollis velit aliquet, volutpat egestas metus varius. In tristique vitae enim vel mollis. Maecenas venenatis nibh vitae quam tincidunt pharetra. Nulla vestibulum lacus velit, at gravida massa varius nec. Phasellus vitae sapien quis nibh efficitur mollis. Curabitur aliquam neque nec augue elementum, a fermentum mi tincidunt. In augue elit, ultricies sed porttitor ut, pulvinar a sapien. Phasellus ut eros diam. Aenean vel pretium orci. Donec diam elit, suscipit quis nisl vel, varius consequat neque."],
  ],
}

const sampleDataZ = {
  '2018-07-17' : [
    ["i", "23523/ 4534533", "СТАТУС 21", "09.07.2018", "Иван Иванов", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "23451/ 5353577", "СТАТУС 22", "09.07.2018", "Георги Георгиев", "In hac habitasse platea dictumst. Vestibulum faucibus elit vitae iaculis cursus. Sed porttitor ex velit, eu sollicitudin nunc sollicitudin quis. Donec id arcu vel ex tempus varius et non ex. Praesent eu pretium diam. Donec in dapibus neque. Nunc malesuada vestibulum luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dapibus ac tellus at ultrices. Donec neque diam, rutrum nec malesuada eget, consequat ac diam."],
    ["i", "23423/ 9894367", "СТАТУС 8", "09.07.2018", "Иванка Иванова", "Morbi pellentesque urna mollis velit aliquet, volutpat egestas metus varius. In tristique vitae enim vel mollis. Maecenas venenatis nibh vitae quam tincidunt pharetra. Nulla vestibulum lacus velit, at gravida massa varius nec. Phasellus vitae sapien quis nibh efficitur mollis. Curabitur aliquam neque nec augue elementum, a fermentum mi tincidunt. In augue elit, ultricies sed porttitor ut, pulvinar a sapien. Phasellus ut eros diam. Aenean vel pretium orci. Donec diam elit, suscipit quis nisl vel, varius consequat neque."],
  ],
  '2018-07-09' : [
    ["i", "23523/ 4534533", "СТАТУС 21", "09.07.2018", "Иван Иванов", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "23451/ 5353577", "СТАТУС 22", "09.07.2018", "Георги Георгиев", "In hac habitasse platea dictumst. Vestibulum faucibus elit vitae iaculis cursus. Sed porttitor ex velit, eu sollicitudin nunc sollicitudin quis. Donec id arcu vel ex tempus varius et non ex. Praesent eu pretium diam. Donec in dapibus neque. Nunc malesuada vestibulum luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dapibus ac tellus at ultrices. Donec neque diam, rutrum nec malesuada eget, consequat ac diam."],
    ["i", "23423/ 9894367", "СТАТУС 8", "09.07.2018", "Иванка Иванова", "Morbi pellentesque urna mollis velit aliquet, volutpat egestas metus varius. In tristique vitae enim vel mollis. Maecenas venenatis nibh vitae quam tincidunt pharetra. Nulla vestibulum lacus velit, at gravida massa varius nec. Phasellus vitae sapien quis nibh efficitur mollis. Curabitur aliquam neque nec augue elementum, a fermentum mi tincidunt. In augue elit, ultricies sed porttitor ut, pulvinar a sapien. Phasellus ut eros diam. Aenean vel pretium orci. Donec diam elit, suscipit quis nisl vel, varius consequat neque."],
  ],
  '2018-07-10' : [
    ["i", "36453/ 1456465", "СТАТУС 2", "10.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
  ],
  '2018-07-11' : [
    ["i", "36453/ 1456465", "СТАТУС 2", "11.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "34534/ 7678985", "СТАТУС 5", "11.07.2018", "Трайчо Трайков", "Nulla tempor orci elit, vitae gravida nulla placerat id. Aliquam sodales lorem a arcu dapibus eleifend vitae vitae est. Nunc finibus lectus vel sem ullamcorper lobortis. In ut ultrices erat. Cras porttitor finibus diam nec luctus. Suspendisse in augue ipsum. Suspendisse potenti. Maecenas et eros ac nisl bibendum tincidunt nec eget leo. Sed sit amet neque eget justo condimentum convallis. Cras eget nisl laoreet, dapibus libero at, vulputate arcu. In dictum lacinia orci, nec dignissim dolor ultricies at. Integer ullamcorper, nisi non mattis iaculis, dolor massa mattis lacus, sollicitudin feugiat orci nisi sed nulla. Mauris quis tristique nibh, sit amet scelerisque nibh."],
    ["i", "01312/ 4531135", "СТАТУС 21", "11.07.2018", "Здравко Здравков", "Sed molestie commodo nibh, quis tincidunt arcu dapibus vitae. Sed enim urna, interdum id auctor non, rutrum volutpat nulla. Etiam ut cursus magna, eget malesuada sapien. Nulla finibus tortor finibus leo molestie faucibus. Integer vel sapien porta, pellentesque felis sed, fermentum arcu. Suspendisse a massa ante. Nunc euismod nisl eros, ut pretium odio consequat ac."],
    ["i", "46783/ 4537837", "СТАТУС 24", "11.07.2018", "Желязко Желязков", "Sed felis dui, finibus nec suscipit vel, blandit ut sapien. Cras ornare odio elit, sed dignissim urna egestas hendrerit. Maecenas aliquam enim vitae commodo rhoncus. In porttitor ullamcorper felis, quis sodales neque eleifend ut. Sed non tellus libero. Mauris in quam id nulla dignissim commodo ac nec tellus. Nullam sagittis pellentesque neque ut dictum. Ut tristique, quam sit amet consequat porta, mi nisl lacinia felis, sit amet auctor turpis dolor quis arcu. Donec quis mi nec est elementum condimentum. Vestibulum luctus pretium euismod. Aliquam ut justo sed orci faucibus imperdiet. Quisque quis erat lacinia, egestas lorem ut, mollis mauris. In convallis at nisi aliquet laoreet. Nulla aliquam consequat gravida. Nullam sollicitudin a orci ut congue. Aliquam sed quam blandit, euismod enim eu, luctus sapien."],
    ["i", "23523/ 4534533", "СТАТУС 21", "11.07.2018", "Иван Иванов", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "23451/ 5353577", "СТАТУС 22", "11.07.2018", "Георги Георгиев", "In hac habitasse platea dictumst. Vestibulum faucibus elit vitae iaculis cursus. Sed porttitor ex velit, eu sollicitudin nunc sollicitudin quis. Donec id arcu vel ex tempus varius et non ex. Praesent eu pretium diam. Donec in dapibus neque. Nunc malesuada vestibulum luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dapibus ac tellus at ultrices. Donec neque diam, rutrum nec malesuada eget, consequat ac diam."],
    ["i", "23423/ 9894367", "СТАТУС 8", "11.07.2018", "Иванка Иванова", "Morbi pellentesque urna mollis velit aliquet, volutpat egestas metus varius. In tristique vitae enim vel mollis. Maecenas venenatis nibh vitae quam tincidunt pharetra. Nulla vestibulum lacus velit, at gravida massa varius nec. Phasellus vitae sapien quis nibh efficitur mollis. Curabitur aliquam neque nec augue elementum, a fermentum mi tincidunt. In augue elit, ultricies sed porttitor ut, pulvinar a sapien. Phasellus ut eros diam. Aenean vel pretium orci. Donec diam elit, suscipit quis nisl vel, varius consequat neque."],
    ["i", "36453/ 1456465", "СТАТУС 2", "11.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "34534/ 7678985", "СТАТУС 5", "11.07.2018", "Трайчо Трайков", "Nulla tempor orci elit, vitae gravida nulla placerat id. Aliquam sodales lorem a arcu dapibus eleifend vitae vitae est. Nunc finibus lectus vel sem ullamcorper lobortis. In ut ultrices erat. Cras porttitor finibus diam nec luctus. Suspendisse in augue ipsum. Suspendisse potenti. Maecenas et eros ac nisl bibendum tincidunt nec eget leo. Sed sit amet neque eget justo condimentum convallis. Cras eget nisl laoreet, dapibus libero at, vulputate arcu. In dictum lacinia orci, nec dignissim dolor ultricies at. Integer ullamcorper, nisi non mattis iaculis, dolor massa mattis lacus, sollicitudin feugiat orci nisi sed nulla. Mauris quis tristique nibh, sit amet scelerisque nibh."],
    ["i", "01312/ 4531135", "СТАТУС 21", "11.07.2018", "Здравко Здравков", "Sed molestie commodo nibh, quis tincidunt arcu dapibus vitae. Sed enim urna, interdum id auctor non, rutrum volutpat nulla. Etiam ut cursus magna, eget malesuada sapien. Nulla finibus tortor finibus leo molestie faucibus. Integer vel sapien porta, pellentesque felis sed, fermentum arcu. Suspendisse a massa ante. Nunc euismod nisl eros, ut pretium odio consequat ac."],
    ["i", "36453/ 1456465", "СТАТУС 2", "11.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "34534/ 7678985", "СТАТУС 5", "11.07.2018", "Трайчо Трайков", "Nulla tempor orci elit, vitae gravida nulla placerat id. Aliquam sodales lorem a arcu dapibus eleifend vitae vitae est. Nunc finibus lectus vel sem ullamcorper lobortis. In ut ultrices erat. Cras porttitor finibus diam nec luctus. Suspendisse in augue ipsum. Suspendisse potenti. Maecenas et eros ac nisl bibendum tincidunt nec eget leo. Sed sit amet neque eget justo condimentum convallis. Cras eget nisl laoreet, dapibus libero at, vulputate arcu. In dictum lacinia orci, nec dignissim dolor ultricies at. Integer ullamcorper, nisi non mattis iaculis, dolor massa mattis lacus, sollicitudin feugiat orci nisi sed nulla. Mauris quis tristique nibh, sit amet scelerisque nibh."],
    ["i", "01312/ 4531135", "СТАТУС 21", "11.07.2018", "Здравко Здравков", "Sed molestie commodo nibh, quis tincidunt arcu dapibus vitae. Sed enim urna, interdum id auctor non, rutrum volutpat nulla. Etiam ut cursus magna, eget malesuada sapien. Nulla finibus tortor finibus leo molestie faucibus. Integer vel sapien porta, pellentesque felis sed, fermentum arcu. Suspendisse a massa ante. Nunc euismod nisl eros, ut pretium odio consequat ac."],
  ],
  '2018-07-12' : [
    ["i", "36453/ 1456465", "СТАТУС 2", "12.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "46783/ 4537837", "СТАТУС 24", "12.07.2018", "Желязко Желязков", "Sed felis dui, finibus nec suscipit vel, blandit ut sapien. Cras ornare odio elit, sed dignissim urna egestas hendrerit. Maecenas aliquam enim vitae commodo rhoncus. In porttitor ullamcorper felis, quis sodales neque eleifend ut. Sed non tellus libero. Mauris in quam id nulla dignissim commodo ac nec tellus. Nullam sagittis pellentesque neque ut dictum. Ut tristique, quam sit amet consequat porta, mi nisl lacinia felis, sit amet auctor turpis dolor quis arcu. Donec quis mi nec est elementum condimentum. Vestibulum luctus pretium euismod. Aliquam ut justo sed orci faucibus imperdiet. Quisque quis erat lacinia, egestas lorem ut, mollis mauris. In convallis at nisi aliquet laoreet. Nulla aliquam consequat gravida. Nullam sollicitudin a orci ut congue. Aliquam sed quam blandit, euismod enim eu, luctus sapien."],
    ["i", "23523/ 4534533", "СТАТУС 21", "12.07.2018", "Иван Иванов", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "23423/ 9894367", "СТАТУС 8", "12.07.2018", "Иванка Иванова", "Morbi pellentesque urna mollis velit aliquet, volutpat egestas metus varius. In tristique vitae enim vel mollis. Maecenas venenatis nibh vitae quam tincidunt pharetra. Nulla vestibulum lacus velit, at gravida massa varius nec. Phasellus vitae sapien quis nibh efficitur mollis. Curabitur aliquam neque nec augue elementum, a fermentum mi tincidunt. In augue elit, ultricies sed porttitor ut, pulvinar a sapien. Phasellus ut eros diam. Aenean vel pretium orci. Donec diam elit, suscipit quis nisl vel, varius consequat neque."],
  ],
  '2018-07-13' : [
    ["i", "36453/ 1456465", "СТАТУС 2", "13.07.2018", "ВЛАДИСЛАВ ГАНЕВ", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "34534/ 7678985", "СТАТУС 5", "13.07.2018", "Трайчо Трайков", "Nulla tempor orci elit, vitae gravida nulla placerat id. Aliquam sodales lorem a arcu dapibus eleifend vitae vitae est. Nunc finibus lectus vel sem ullamcorper lobortis. In ut ultrices erat. Cras porttitor finibus diam nec luctus. Suspendisse in augue ipsum. Suspendisse potenti. Maecenas et eros ac nisl bibendum tincidunt nec eget leo. Sed sit amet neque eget justo condimentum convallis. Cras eget nisl laoreet, dapibus libero at, vulputate arcu. In dictum lacinia orci, nec dignissim dolor ultricies at. Integer ullamcorper, nisi non mattis iaculis, dolor massa mattis lacus, sollicitudin feugiat orci nisi sed nulla. Mauris quis tristique nibh, sit amet scelerisque nibh."],
    ["i", "01312/ 4531135", "СТАТУС 21", "13.07.2018", "Здравко Здравков", "Sed molestie commodo nibh, quis tincidunt arcu dapibus vitae. Sed enim urna, interdum id auctor non, rutrum volutpat nulla. Etiam ut cursus magna, eget malesuada sapien. Nulla finibus tortor finibus leo molestie faucibus. Integer vel sapien porta, pellentesque felis sed, fermentum arcu. Suspendisse a massa ante. Nunc euismod nisl eros, ut pretium odio consequat ac."],
    ["i", "46783/ 4537837", "СТАТУС 24", "13.07.2018", "Желязко Желязков", "Sed felis dui, finibus nec suscipit vel, blandit ut sapien. Cras ornare odio elit, sed dignissim urna egestas hendrerit. Maecenas aliquam enim vitae commodo rhoncus. In porttitor ullamcorper felis, quis sodales neque eleifend ut. Sed non tellus libero. Mauris in quam id nulla dignissim commodo ac nec tellus. Nullam sagittis pellentesque neque ut dictum. Ut tristique, quam sit amet consequat porta, mi nisl lacinia felis, sit amet auctor turpis dolor quis arcu. Donec quis mi nec est elementum condimentum. Vestibulum luctus pretium euismod. Aliquam ut justo sed orci faucibus imperdiet. Quisque quis erat lacinia, egestas lorem ut, mollis mauris. In convallis at nisi aliquet laoreet. Nulla aliquam consequat gravida. Nullam sollicitudin a orci ut congue. Aliquam sed quam blandit, euismod enim eu, luctus sapien."],
    ["i", "23523/ 4534533", "СТАТУС 21", "13.07.2018", "Иван Иванов", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra tincidunt enim ac maximus. Mauris hendrerit eleifend ipsum, nec luctus tortor. Mauris arcu felis, suscipit sit amet ullamcorper nec, congue ac leo. Donec tincidunt et risus vitae varius. Suspendisse iaculis, leo non pellentesque condimentum, mi arcu imperdiet eros, sit amet posuere leo risus ac sapien. Integer quis ante eu erat suscipit imperdiet. Aliquam erat volutpat. Proin aliquam tellus non eros iaculis, non efficitur mauris porta. Vestibulum diam nisi, facilisis ut molestie ac, tempor vitae ex. Etiam sed ligula quam. Vivamus nec malesuada est. Maecenas facilisis non nisl sit amet pharetra. Duis ornare luctus tortor non congue. Nunc iaculis nunc libero, et scelerisque risus commodo ac. Proin pharetra iaculis tellus ut euismod."],
    ["i", "23451/ 5353577", "СТАТУС 22", "13.07.2018", "Георги Георгиев", "In hac habitasse platea dictumst. Vestibulum faucibus elit vitae iaculis cursus. Sed porttitor ex velit, eu sollicitudin nunc sollicitudin quis. Donec id arcu vel ex tempus varius et non ex. Praesent eu pretium diam. Donec in dapibus neque. Nunc malesuada vestibulum luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dapibus ac tellus at ultrices. Donec neque diam, rutrum nec malesuada eget, consequat ac diam."],
    ["i", "23423/ 9894367", "СТАТУС 8", "13.07.2018", "Иванка Иванова", "Morbi pellentesque urna mollis velit aliquet, volutpat egestas metus varius. In tristique vitae enim vel mollis. Maecenas venenatis nibh vitae quam tincidunt pharetra. Nulla vestibulum lacus velit, at gravida massa varius nec. Phasellus vitae sapien quis nibh efficitur mollis. Curabitur aliquam neque nec augue elementum, a fermentum mi tincidunt. In augue elit, ultricies sed porttitor ut, pulvinar a sapien. Phasellus ut eros diam. Aenean vel pretium orci. Donec diam elit, suscipit quis nisl vel, varius consequat neque."],
  ],
}

export default class Dashboard extends React.Component {
  constructor(props) {
    super(props);
    this.state = { 
      selectedDate: new Date().toISOString().slice(0,10),
      navbarTabId: 'edit',
    };
  }
  render() {
    return (
      <div>
        <Row>
          <Col span={2}>
            <DatePicker 
              onChange={(newDate) => this.handleNewDate(newDate)}
              localeUtils={MomentLocaleUtils} 
              locale='bg'
              showActionsBar="true"
            />
          </Col>
            <Col span={10}>
            <h2>Данни X за {this.state.selectedDate.toString()}</h2>
            <TableComponent data={sampleDataX[this.state.selectedDate]} />

            <h2 style={{'paddingTop':'20px'}}>Данни Y за {this.state.selectedDate.toString()}</h2>
            <ReordableTable data={sampleDataY[this.state.selectedDate]} />

            <h2 style={{'paddingTop':'20px'}}>Данни Z за {this.state.selectedDate.toString()}</h2>
            <SortableTable data={sampleDataZ[this.state.selectedDate]} />
          </Col>
        </Row>
        <Row>
          <Col span={6} offset={3} style={{'paddingTop':'20px'}}>
            <Card interactive={true} elevation={Elevation.TWO}>
              <Tabs id="TabsExample" onChange={this.handleTabChange} selectedTabId={this.state.navbarTabId}>
                <Tab id="edit" title="Редактирай профил" panel={<EditProfilePanel />} />
                <Tab id="extra" title="Допълнителна информация" panel={<ExtraInfoPanel />} />
                <Tabs.Expander />
                <input className="bp3-input" type="text" placeholder="Search..." />
              </Tabs>
            </Card>
          </Col>
        </Row>
      </div>     
    )
  }

  handleNewDate(newDate) {
    let date = new Date(newDate).toISOString().slice(0,10);
    if (newDate == null) return;
    this.setState({ 
      selectedDate: date,
      // data: data
    });
  }

  handleTabChange = (navbarTabId) => {
    this.setState({ navbarTabId });
  }
}